In [ ]:
# Setup jupyter notebook for local machine
# /home/piyush/Documents/git1/Machine-Learning-Practice/my_project_env/bin/python -m pip install --upgrade pip
# virtualenv my_project_env
# source my_project_env/bin/activate
# pip install jupyter
# jupyter notebook
# !pip install numpy
import numpy as np
# !pip install pandas
import pandas as pd
# !pip install matplotlib
import matplotlib as mt
# !pip install -U scikit-learn
from sklearn import random_projection

**LOADING DATASET**

In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
digit = datasets.load_digits()

Data : (n_samples, n_features)

In [7]:
print(digit.data)
print(digit.data.shape)
print(digit.images[0])

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
(1797, 64)
[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


Target : (n_samples)

In [6]:
print(digit.target)
print(digit.target.shape)

[0 1 2 ... 8 9 8]
(1797,)
